"""Add password_hash column to User model

Revision ID: 051c3097586f
Revises: 0e632221f2f9
Create Date: 2025-08-10 13:00:44.577454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051c3097586f'
down_revision = '0e632221f2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for existing data ###
    # 检查password_hash列是否存在
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('user')]

    # 1. 如果password_hash列不存在，则添加允许为空的password_hash列
    if 'password_hash' not in columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # 2. 将password列的值复制到password_hash列（如果password列存在）
    if 'password' in columns:
        op.execute('UPDATE user SET password_hash = password')

        # 3. 修改password_hash列为非空
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('password_hash', nullable=False)
            batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
