"""'Add user profile fields'

Revision ID: 7e7e7e508e13
Revises: f3e78b6d7633
Create Date: 2025-08-14 16:21:23.022180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7e7e508e13'
down_revision = 'f3e78b6d7633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('listen_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vip_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vip_level')
        batch_op.drop_column('listen_time')
        batch_op.drop_column('visits')
        batch_op.drop_column('following')
        batch_op.drop_column('followers')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
